server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti
    username: root
    password: root
  activiti:
    async-executor-activate: false
logging:
  level:
    org:
      activiti:
        engine:
          impl:
            persistence:
              entity: trace

